--- #YAML:1.0
name:                Tk-Spectrum
version:             0.02
abstract:            A stylish color selection dialog.
license:             ~
author:              
    - Casey Kirsle <casey at cuvou.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Tk:                            0
    Tk::PNG:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
